# Data file to use
dataFile: "../data/data_mrna_seq_v2_rsem_zscores_ref_diploid_samples.txt"

# Gene set to use
geneSetFile: "./input/defaultGeneSets.txt"

# Output file
resultFile: "../results/gsea1.csv"